### PR TITLE
Use separate arguments instead of colon for option delimiting in -l and -m

### PR DESCRIPTION
**Pull request by maandree**
As discussed way back. Colon is problematic in -m, and separate arguments is a better solution that will not cause problems in the future. The same change is applied -l, so they work in the same way.

### CODE REVIEW

**Comment by jonls** [comment]
@maandree Do you have the reference for the previous discussion? I can't seem to find it right now.

**Comment by jonls** [comment]
Found it: #81

**Comment by jonls** [comment]
I'm not happy about completely changing the way the command line options work in a minor release but I understand that this would be useful for handling individual monitor settings?. Do you think we can handle the settings of the monitors through the configuration file entirely so we don't have to apply this change yet?

**Comment by maandree** [comment]
We don't have to change this yet. I think it should be held until version 2.0 that I think should offer full support for multiple monitors, multiple display and multiple adjustment methods.

**Pull request closed without merging**
