### PR TITLE
Add backlight support

### PR DESCRIPTION
**Pull request by eldipa**
This PR enables the control of the monitor's backlight using sysfs.

Redshift controls the brightness modifying the gamma ramps with `-b`.  
With this PR, the user can activate the backlight support with  `-k` and control the brightness with the same flag `-b`.

The proposed implementation uses a path to the sys file system to control the backlight given as the argument of `-k`:

```
redshift  -b 0.7:0.3   -k /sys/class/backlight/intel_backlight 
```

If `list` is given as the argument for `-k`, the implementation will list all the available controllers inside ` /sys/class/backlight/` so the user can know which he could use.

### Caveats
Because how sysfs works, redshift will need to run with higher privileges. One possible enhancement would to drop any privilege after acquiring the resources needed. 

The other issue, of course, is that this will not work in a Windows environment.

I'm open to hear other alternatives and workaround as well as improvements and suggestions. I really like redshift and it helped me and the backlight support is a nice complement to avoid eyes problems or sleep problems.

If I can contribute with this project in any way, it would be a pleasure for me.

### CODE REVIEW

**Comment by breznak** [comment]
This looks nice :+1: 
Could you please elaborate what is the advantage of the proposed sysfs brightness implementation (compared to the current brightness control)?

**Comment by eldipa** [comment]
Hey, thanks!

Redshift modifies the gamma ramps to give the illusion of a (fake) brightness adjustment.

From the official site:
> Redshift has a brightness adjustment setting, but it does not work the way most people might expect. [...], which means that it does not reduce the backlight of the screen.

That means that the monitor will still emit the same light regardless of the redshift's brightness settings.
If you are working in a dark place, this strategy doesn't work: your monitor will still emit too much light and it will hurt your eyes.

That was the reason to implement this PR: instead of changing the backlight manually it uses sysfs to control the backlight of the monitor by real; it is not an illusion anymore.

The nice of this is that the backlight will change smooth based on the sun elevation like the rest of redshift.

**Comment by breznak** [comment]
Thank you for explanation @eldipa , and that sound as indeed vital improvement! :+1: 
Can you fix the conflicts with `master`? 
Let's hope @jonls can merge this feature soon.

**Comment by rthardy** [comment]
Adjusting brightness through adjusting gamma ramps also reduces contrast.  This is absolutely horrible if you (I) already have a crappy low contrast display.  But I still do it if the dimmest backlight setting isn't dim enough.  That happens when I am outdoors under good stargazing conditions.

**Comment by anarcat** [comment]
I really like the idea of *actually* changing the brightness of the screen, but i'm not sure I like the idea of using a (basically) proprietary interface like this. there are multiple backends to make those changes, and like there are multiple backends to change the gamma, we should support multiple interfaces for brightness as well...

for example, the sysfs approach does not work for external monitors. xbacklight *may* work in some cases, but doesn't work here. the only thing that works here is [ddccontrol](https://github.com/ddccontrol/), which uses a whole different approach. now maybe it's better for me to go through hooks - but then i lose the progressive changes this extension could give me...

one way I can think of to change this would be to extend hooks to fire when transitions happen, with more transition data fed in. for example, during transition, a percentage of the transition could be passed as arguments to the hooks, which could allow us to implement whatever we need depending on the backend.

hardcoded backlight values can already be set with such a hook in `~/.config/redshift/hooks/backlight.sh`:

```
#!/bin/sh

case "$1" in
    night)
        ddccontrol -p -r 0x10 -w 50
        ;;
    daytime)
        ddccontrol -p -r 0x10 -w 100
        ;;
esac
```

**Comment by anarcat** [comment]
also note this relates with #436

**Comment by jonls** [comment]
Thanks for looking into this. It would be nice to support real backlight adjustments. If there's a relatively simple way of implementing it, I think including it in Redshift would make sense. I'm not convinced that sysfs is the right approach though. There is apparently an attribute in RandR that can be used so supporting backlight changes through the adjustment method could be an option _if_ that actually works in practice on a majority of graphics cards/displays.

**Comment by anarcat** [comment]
i agree that operating with the xrandr extension is the best path forward, as it is well supported on laptops. unfortunately I am not sure it would work with external monitors, even if kernel support is added. it might be possible that those things converge eventually though, and maybe we should just rely on that happening instead of hacking this into redshift. for now, i am using hooks and that works fine...

**Comment by Hubro** [comment]
I just want to point out, while you're waiting for a perfect solution, there's currently *no* way to achieve this with Redshift. Wouldn't it be better to accept this pull request as a temporary, opt-in solution with its own flag while we're waiting for a perfect solution? It wouldn't affect anybody negatively, and it would make life a whole lot easier for all that laptop users (like me) who have backlights that can be adjusted with the `sysfs` approach.

**Comment by mirh** [comment]
https://www.kernel.org/doc/html/latest/firmware-guide/acpi/video_extension.html
https://www.kernel.org/doc/Documentation/ABI/stable/sysfs-class-backlight
https://lore.kernel.org/patchwork/patch/528936/#708706

There's nothing proprietary in pinging directly the kernel. That's still what RandR touches when you use xbacklight after all. 

If any one possible issue is that you are required to implement some logic for preferences of hardware interfaces. 
Which if on the one hand, yes, seems something you shouldn't have to reinvent here, [on the other](https://www.spinics.net/lists/linux-acpi/msg45290.html) I'm not sure it is all that much a business that we shouldn't have to care at all even in principle. 

On a single-screen scenario, that's a no-brainer of course. But what's the program supposed to do once you have more than a single monitor? Perhaps even one internal and one [external](https://github.com/jonls/redshift/issues/436), why not on different gpus? 
A very niche scenario, that I'm not arguing should be a priority.. But still something to consider and that asks big question on the software design. 

And of course, I'd like to remember (for [whatever reason](https://bugs.freedesktop.org/show_bug.cgi?id=36257#c5)) the `backlight` [property](https://cgit.freedesktop.org/xorg/proto/randrproto/tree/randrproto.txt?h=randrproto-1.5.0#n1905) xrandr could remotely help with here, is only just supported by [Intel](https://lwn.net/Articles/354796/).

**Pull request closed without merging**
