### PR TITLE
Wayland support PR

### LINKED ISSUE #55: Feature: Add Wayland support
I use a Jolla phone with SailfishOS which already uses Wayland as display server. One thing I'm really missing is color shift in the dark. Is there something similar to the X server extension used for Wayland?

### PR DESCRIPTION
**Pull request by breznak**
Fixes #55

### CODE REVIEW

**Comment by breznak** [comment]
Also, there was another approach shown
https://github.com/danielng01/iris-floss-wayland

**Comment by benmccann** [comment]
@breznak this PR will need a rebase

**Comment by clarcharr** [comment]
Any update on this? I've been using the fork at <Lourens-Rich/redshift> which is horribly out of date.

**Comment by breznak** [comment]
Closing this branch, it is continued in PR #568

**Pull request closed without merging**
