### PR TITLE
Formatted help text paragraph to 80 chars max

### PR DESCRIPTION
**Pull request by faheel**
I think I would also need to make changes to the `redshift.1` file [here](https://github.com/jonls/redshift/blob/master/redshift.1#L75-L79) and the translation files, though I'm not sure.

### CODE REVIEW

**Comment by jonls** [comment]
@faheel Thanks! The man page source does not need to be modified I think, because man will automatically extend and wrap paragraphs at the line width. The source file `redshift.c` should also be limited to 80 character lines though.

**Comment by faheel** [comment]
I see. It would be tricky to get the lines in the source code too to be limited to 80 chars while maintaining proper indentaion, as the strings themselves are close to 80 chars (the longest one being of 79 chars).
The only solution I see is that we can keep the lines as they were, changing only the `\n` at the end to a space so that the text will extend to the width of the terminal, but would lose the 80 char limit (even though it will be consistent with the man page). What do you suggest?

**Comment by jonls** [comment]
Yeah, just break the string literal before the "\n" (like "help output 2").

**Comment by jonls** [comment]
@faheel Thanks 👍

**Pull request merged**
