### PR TITLE
x86 builds for windows

### LINKED ISSUE #342: Windows 32-bit release
Any plans for a 32 bit windows release?

### PR DESCRIPTION
**Pull request by manuc66**
This PR allows i686 build on appveyor for Windows.

fix #342

### CODE REVIEW

**Comment by jonls** [comment]
Thanks! Can you update the links in the README file too (i.e. add a link to "Windows x86")?

**Comment by manuc66** [comment]
@jonls  done ;-)

**Comment by jonls** [comment]
@manuc66 Hmm, it seems that the link has to be specified in a different way since there are now multiple jobs. See my test here: https://ci.appveyor.com/api/projects/jonls/redshift/artifacts/redshift-windows-x86_64.zip?branch=appveyor-x86-builds The error message is: `"job" parameter must be specified if build contains multiple jobs.`. It seems that the job name has to be specified but the job name is rather long and has to be properly URL encoded (e.g. for x64 the job name would be "Environment: arch=x86_64, HOST_ARCH_ARG=--host=x86_64-w64-mingw32, ADD_PATH_CMD=C:\msys64\usr\bin;C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin, MSYSTEM=MINGW64").

Maybe we could set only `arch` in the `matrix` section, then set the remaining environment variables at the beginning of `build_script`? Something like, `if "%arch%" == "x86_64" $env:HOST_ARCH_ARG = "--host=x86_64-w64-mingw32" etc. (I'm not sure if this is the right syntax).

**Comment by manuc66** [comment]
Opps, sorry, link fixed!

**Comment by jonls** [comment]
Thanks, looks good. I tested again and found another issue: If I click the links right now (with `branch=master`) it seems that they already work! This is surprising since the pull request has not been merged into master yet. It seems that AppVeyor builds the merge commit on the master branch when a pull request is submitted so essentially the links would point to the artifacts from the last pull request not the last commit on master. I'm wondering if we need something like `skip_branch_with_pr` as mentioned here: https://github.com/appveyor/ci/issues/882

**Comment by jonls** [comment]
@manuc66 Actually, it seems that this can be fixed by setting `pr=false` on the links: https://www.appveyor.com/docs/packaging-artifacts/#permalink-to-the-last-successful-build-artifact

**Comment by jonls** [comment]
Thanks! Squashed and merged as 2a253869462efca5348796e317ebfae2df3c81a9

**Pull request closed without merging**
