### PR TITLE
Inhibit redshift when fullscreen app detected (redshift-gtk only)

### PR DESCRIPTION
**Pull request by getzze**
This adds a checkbox in the status icon and a command-line argument `-f` for redshift-gtk to detect fullscreen app and inhibit redshift (for exemple when watching a movie).
It adds a dependency to the `[ewmh](https://pypi.python.org/pypi/ewmh/)` python module to detect fullscreen apps.

### CODE REVIEW

**Comment by yerbestpal** [comment]
Pardon my ignorance and unfamiliarity with Github, but is this now an integrated feature?

**Comment by maandree** [comment]
No, here is an example of how it would look if it was: https://github.com/jonls/redshift/pull/426

**Comment by iKenshu** [comment]
So, how can I made this works?

**Comment by jonls** [comment]
@iKenshu Try out the code in this PR if you can, and report any results. To get this PR into Redshift I think a rebase on the master branch is needed.

**Comment by akarl818** [comment]
Would be nice to be able to whitelist the fullscreen apps that you want to have this for. For example I have a dark theme for my terminal which I run in fullscreen and I would like to disable redshift when for that, but not for my Chrome which I also run in fullscreen.

**Comment by jonls** [comment]
This is not a bad idea but I think this can be implemented without continuously polling for `_NET_WM_STATE_FULLSCREEN`. In any case, the CI builds are failing so this should be cleaned up to move forward.

**Comment by kepler2** [comment]
Hello all :)

First of all thanks for all your work.

Is there any update on this?

I've saw a similar function in f.lux. Basically when you enter full screen mode (watch a youtube video, vlc full video etc.) it automatically disables.

Is there a way to add this feature to redshift? Or at least a shortcut for the Redshift GTK tray icon?

Thanks!

**Comment by Ph0rkoz** [comment]
Really wish this was a thing. I don't want chrome blasting me with white... but I want to fullscreen the videos without color shifts.

**Comment by dvof** [comment]
Yes looking forward towards this, when I use flux on windows I can put a vid on one of my monitors in fullscreen (with flux disabled) while I'm working on another monitor (with flux enabled). Now that I don't have it it really feels like a necessity

**Pull request closed without merging**
