### PR TITLE
Fix #121: Handle multiple monitors on Windows

### LINKED ISSUE #121: Random temperature adjustment failure using WinGDI (windows)
Getting some errors trying to run on the Windows Technical Preview.

```
C:\Users\Danny\Downloads>redshift -v -c C:\Users\Danny\Documents\redshift.conf
Location: 0, 0
Temperatures: 6500K at day, 5000K at night
Brightness: 1.00:1.00
Gamma: 1.000, 1.000, 1.000
Status: Enabled
Period: Night
Color temperature: 6500K
Brightness: 1.00
Period: Night
Color temperature: 6484K
Brightness: 1.00
Unable to set gamma ramps.
Temperature adjustment failed.
```

Here is my config:

```
; Global settings for redshift
[redshift]
; Set the day and night screen temperatures
temp-day=6500
temp-night=5000

; Enable/Disable a smooth transition between day and night
; 0 will cause a direct change from day to night screen temperature. 
; 1 will gradually increase or decrease the screen temperature
transition=1

; Set the screen brightness. Default is 1.0
;brightness=0.9
; It is also possible to use different settings for day and night since version 1.8.
;brightness-day=0.7
;brightness-night=0.4
; Set the screen gamma (for all colors, or each color channel individually)
;gamma=0.8
;gamma=0.8:0.7:0.8

; Set the location-provider: 'geoclue', 'gnome-clock', 'manual'
; type 'redshift -l list' to see possible values
; The location provider settings are in a different section.
location-provider=manual

; Set the adjustment-method: 'randr', 'vidmode'
; type 'redshift -m list' to see all possible values
; 'randr' is the preferred method, 'vidmode' is an older API
; but works in some cases when 'randr' does not.
; The adjustment method settings are in a different section.
adjustment-method=wingdi

; Configuration of the location-provider:
; type 'redshift -l PROVIDER:help' to see the settings
; ex: 'redshift -l manual:help'
[manual]
lat=0
lon=0

; Configuration of the adjustment-method
; type 'redshift -m METHOD:help' to see the settings
; ex: 'redshift -m randr:help'
; In this example, randr is configured to adjust screen 1. 
; Note that the numbering starts from 0, so this is actually the second screen.
[randr]
screen=0
```

### PR DESCRIPTION
**Pull request by arnej**

### CODE REVIEW

**Comment by LeoColomb** [comment]
:+1: Like a charm!

**Comment by Nepochal** [comment]
Works great. Tested with 2 monitors on Windows 7.

**Comment by jonls** [comment]
This should perhaps also save all the gamma ramps in `w32gdi_start()` so they can be restored at the end?

**Comment by arnej** [comment]
Good idea. I'll do that and test it on my work computer :)

**Comment by gliptak** [comment]
Could this be merged for the next Win release? Thanks

**Comment by arnej** [comment]
I'm currently busy with other things so it may take some time until I can add the proposed saving of the gamma ramps. If someone else wants to add this change, feel free to do so.

**Comment by dev7355608** [comment]
This won't fix #121. And there are a couple of things wrong with this code.

1. `CreateDC` must _not_ be destroyed with `ReleaseDC` but with `DeleteDC`.
2. No device context created from a display device  might support gamma ramps but `GetDC(NULL)` could.
3. You can hold on to the device context created by `CreateDC` and don't have to create and destroy it every time.

Another thing: you can use [`CreateIC`](https://msdn.microsoft.com/en-us/library/dd183505(v=vs.85).aspx) instead of `CreateDC`. It's cheaper and setting the gamma ramp is still possible.

**Comment by diegorodriguezv** [comment]
Hi. It seems to me this bug should be closed. I'm now able to use redshift with 2 monitors in windows 8.1 beginning with version 1.11 (turning it into a kick ass multi platform software!). Thank you very,very much! My eyes missed this a lot in windows.

**Comment by diegorodriguezv** [comment]
Sorry. Version 1.11 wasn't available for windows. I was referring to the master branch build. Maybe mark this as 1.12 milestone?

**Comment by jonls** [comment]
This might be fixed already so closing. If not, this PR should be updated with the requested changes.

**Pull request closed without merging**
