### PR TITLE
Add an icon for the Windows executable

### PR DESCRIPTION
**Pull request by manuc66**
The .ico has been generated with :
```bash
convert redshift.svg -background none -bordercolor white -border 0 \
          \( -clone 0 -resize 16x16 \) \
          \( -clone 0 -resize 32x32 \) \
          \( -clone 0 -resize 48x48 \) \
          \( -clone 0 -resize 64x64 \) \
          \( -clone 0 -resize 256x256 \) \
          -delete 0 -alpha off -colors 256 redshift.ico
```
It uses https://github.com/electron/rcedit to set the icon after the build.

### CODE REVIEW

**Comment by jonls** [comment]
@manuc66 Thanks! It seems that the icon can also be bundled using the `windres` tool in MinGW. I think using `windres` may be preferable to avoid relying on the external `rcedit` tool. I made a test of this approach in https://github.com/jonls/redshift/compare/windows-resources (build here: https://ci.appveyor.com/project/jonls/redshift/build/1.0.53/job/2xx9hgdjfr7eddwp/artifacts). What do you think?

**Comment by manuc66** [comment]
@jonls I did not know how to use ``windres`` and so I looked for the simpler way to do it.

No problem for me to use ``windres`` instead, here is how it looks on win-x64:

**Comment by manuc66** [comment]
@jonls I'm currently trying to improve the look of the icon, I thinks it looks too blurred

**Comment by manuc66** [comment]
@jonls it looks really better now:

**Comment by jonls** [comment]
@manuc66 Yes, that looks better. How much does this increase the size of the final exe? Also, does this work with non-white background (in other words, is the icon background transparent or white?).

**Comment by manuc66** [comment]
The icon is 85ko, the exe is 278k (before it was ~236ko) and the icon background is transparent:

**Comment by jonls** [comment]
@manuc66 Ok, great! What was the final `convert` command?

**Comment by manuc66** [comment]
@jonls I confirm that the command is:
```bash
convert -background none -density 1000 -resize 1000x redshift.svg redshift1000.png
convert redshift1000.png -resize 256x256 redshift256.png
convert redshift256.png -define icon:auto-resize=16,32,48,64,256 -compress zip redshift.ico
```
inspiration sources:
- https://stackoverflow.com/questions/18192250/convert-and-resize-svg-to-png
- https://stackoverflow.com/a/34958537/77135

**Comment by manuc66** [comment]
#490 integrate the icon without relying on external component. Closing this one.

**Pull request closed without merging**
