### PR TITLE
Refactoring (in progress...)

### PR DESCRIPTION
**Pull request by pik**
This is still ongoing and a little messy - but I got `main()` down to about 60 loc. The redshift.c file would be a lot more manageable if some of the stuff got moved out -- potentially all conditional gamma stuff could perhaps go into redshift-gamma.h? Transition_scheme_t and it's associated functions can get their own file as well (redshift-transition.c or transition.c)? It would be quite nice to cut the main file down to under 1000 loc.

I added a general `redshift_state_t` type - it makes passing things around a little cleaner and it'll be quite a bit easier to handle multi-monitor setups / dbus options with it. 

Also I replaced the `mode` enums with flags, the mode setting was quite limiting and made the conditionals kind of strange since redshift was limited to checking for a single mode (that can still be cleaned up more), also I added `APPLY` flags -- this will hopefully make redshift.c forward compatibility with dbus-mode easier, so that targeted changes can be made to the state of a running daemon. 

Some stuff is still interdependent which should be optional e.g. `redshift_state_set_from_config` should be ignorable on `-O` commands,

### CODE REVIEW

**Comment by maandree** [comment]
I recommend not doing reload in this patch. Keep refactoring and new features separate.

**Comment by pik** [comment]
OK how do you feel about various parts of the re-org (sorry the commit history isn't actually very clean I'll rebase) and splitting it into a number of PR's working might make sense as well. 

Also how do you feel about [settings](https://github.com/jonls/redshift/pull/96/files#diff-857580bc1b624f434924371da1390f86R49) vs [redshift_state_t](https://github.com/pik/redshift/blob/develop/src/redshift.c#L78) . Having both seems somewhat redundant since they are more or less accomplishing the same thing but idk.

**Comment by maandree** [comment]
Split into as many pull requests you can.

I am not sure about the settings_t versus redshift_state_t issue. However, if you try to keep it what I have done, it will be easier for me to bring my patches up to date without our patch conflicting too much. Final refactoring can be done later, just keep a list of what you hade to skip.

**Comment by maandree** [comment]
settings_t is based on how old redshift code, ignore it.

**Pull request closed without merging**
